# Generated by Django 4.0b1 on 2021-11-03 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journaly', '0003_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='id',
            new_name='IDNum',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='journal',
            new_name='Journal',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='list',
            new_name='List',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='status',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='time',
            new_name='Time',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='title',
            new_name='Title',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='type',
            new_name='Type',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='user',
            new_name='User',
        ),
        migrations.RemoveField(
            model_name='item',
            name='body',
        ),
        migrations.AddField(
            model_name='item',
            name='Body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
