# Generated by Django 4.0b1 on 2021-11-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journaly', '0004_rename_date_item_date_rename_id_item_idnum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Status',
            field=models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending')], max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='Type',
            field=models.CharField(choices=[('task', 'Task'), ('event', 'Event'), ('note', 'Note')], max_length=10),
        ),
    ]
