# Generated by Django 4.0b1 on 2021-11-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journaly', '0005_alter_item_status_alter_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Type',
            field=models.CharField(choices=[('Task', 'Task'), ('Event', 'Event'), ('Note', 'Note')], max_length=10),
        ),
    ]
