# Generated by Django 4.0b1 on 2021-11-14 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journaly', '0007_alter_item_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='item',
            old_name='IDNum',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='item',
            name='List',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='journaly.list'),
        ),
    ]
