# Generated by Django 4.0b1 on 2021-11-14 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journaly', '0008_list_rename_idnum_item_id_alter_item_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='List',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='journaly.list'),
        ),
    ]
