# Generated by Django 4.0b1 on 2021-11-14 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journaly', '0009_alter_item_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='id',
            new_name='IDNum',
        ),
    ]
