# Generated by Django 4.0b1 on 2021-11-14 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journaly', '0010_rename_id_item_idnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='list',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
