# Generated by Django 4.0b1 on 2021-11-14 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journaly', '0011_list_name_alter_list_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='date_created',
            field=models.DateField(blank=True, null=True),
        ),
    ]
