# Generated by Django 4.0b1 on 2021-11-17 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journaly', '0012_alter_list_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_created', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='List',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='journaly.list'),
        ),
        migrations.AlterField(
            model_name='item',
            name='Journal',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='journaly.journal'),
        ),
    ]
