# Generated by Django 4.0b1 on 2021-11-17 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journaly', '0013_journal_alter_item_list_alter_item_journal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journaly.journal'),
        ),
    ]
