# Generated by Django 4.0b1 on 2021-11-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journaly', '0014_alter_item_journal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Body',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Journal',
            new_name='journal',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Time',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='User',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='item',
            name='IDNum',
        ),
        migrations.RemoveField(
            model_name='item',
            name='List',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Title',
        ),
        migrations.AddField(
            model_name='item',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='title',
            field=models.CharField(default='Untitled', max_length=100),
        ),
    ]
