# Generated by Django 4.0b1 on 2021-11-19 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journaly', '0015_rename_body_item_body_rename_date_item_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='List',
        ),
    ]
