# Generated by Django 4.0b1 on 2021-11-20 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journaly', '0016_delete_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='journaly.user'),
            preserve_default=False,
        ),
    ]
